format = """
[](#181926)\
$os\
$username\
[](bg:#89DCEB fg:#181926)\
$directory\
[](fg:#89DCEB bg:#F38BA8)\
$git_branch\
$git_status\
[](fg:#F38BA8 bg:#A6E3A1)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#A6E3A1 bg:#06969A)\
$docker_context\
[](fg:#06969A bg:#BBA6F7)\
$time\
[ ](fg:#BBA6F7)
($character)
"""
[character]
success_symbol = '[󰄾](#00ff00)'
error_symbol= '[󰄽](#ff0000)'
# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#181926 fg:#EFDA4D" 
style_root = "bg:#181926"
format = '[  $user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#181926"
disabled = true # Disabled by default

[directory]
style = "bg:#89DCEB"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "
[c]
symbol = " "
style = "bg:#A6E3A1"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#A6E3A1"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#A6E3A1"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#F38BA8"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#F38BA8"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#A6E3A1"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#A6E3A1"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#A6E3A1"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#A6E3A1"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#A6E3A1"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#A6E3A1"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#A6E3A1"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:A6E3A1"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:A6E3A1"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#BBA6F7"
format = '[ ♥ $time ]($style)'
